[package]
name = "rasset"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4"] }
